# Generated by Django 5.0.1 on 2026-01-04 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topmate_username', models.CharField(blank=True, max_length=100)),
                ('html_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('interview_data', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_instruction', models.TextField()),
                ('html_before', models.TextField()),
                ('html_after', models.TextField()),
                ('edit_type', models.CharField(blank=True, max_length=50)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='projects.websiteproject')),
            ],
            options={
                'db_table': 'edit_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
